# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/withpwn/VE280-Lab-7-SU2020

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/withpwn/VE280-Lab-7-SU2020

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/withpwn/VE280-Lab-7-SU2020/CMakeFiles /Users/withpwn/VE280-Lab-7-SU2020/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/withpwn/VE280-Lab-7-SU2020/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ve280_lab7

# Build rule for target.
ve280_lab7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ve280_lab7
.PHONY : ve280_lab7

# fast build rule for target.
ve280_lab7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/build
.PHONY : ve280_lab7/fast

course.o: course.cpp.o

.PHONY : course.o

# target to build an object file
course.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/course.cpp.o
.PHONY : course.cpp.o

course.i: course.cpp.i

.PHONY : course.i

# target to preprocess a source file
course.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/course.cpp.i
.PHONY : course.cpp.i

course.s: course.cpp.s

.PHONY : course.s

# target to generate assembly for a file
course.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/course.cpp.s
.PHONY : course.cpp.s

test/simpletest.o: test/simpletest.cpp.o

.PHONY : test/simpletest.o

# target to build an object file
test/simpletest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/test/simpletest.cpp.o
.PHONY : test/simpletest.cpp.o

test/simpletest.i: test/simpletest.cpp.i

.PHONY : test/simpletest.i

# target to preprocess a source file
test/simpletest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/test/simpletest.cpp.i
.PHONY : test/simpletest.cpp.i

test/simpletest.s: test/simpletest.cpp.s

.PHONY : test/simpletest.s

# target to generate assembly for a file
test/simpletest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve280_lab7.dir/build.make CMakeFiles/ve280_lab7.dir/test/simpletest.cpp.s
.PHONY : test/simpletest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ve280_lab7"
	@echo "... course.o"
	@echo "... course.i"
	@echo "... course.s"
	@echo "... test/simpletest.o"
	@echo "... test/simpletest.i"
	@echo "... test/simpletest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

